/*
 * STM32 HAL UART Echo Example
 *
 * This file contains the main loop code to be inserted into a CubeMX generated
 * project.
 *
 * Hardware Setup:
 * - STM32 Nucleo/Discovery Board (e.g., STM32F4, L4, G0)
 * - USB-to-UART Bridge (often built-in to Nucleo boards via ST-Link)
 *
 * CubeMX Configuration:
 * 1. Connectivity -> USART2 (typical for Nucleo USB) -> Mode: Asynchronous.
 * 2. Parameter Settings -> Baud Rate: 115200, Word Length: 8 Bits, Parity:
 * None, Stop Bits: 1.
 * 3. DMA Settings (Optional): Add USART2_RX and USART2_TX for better
 * performance (not used in this simple polling example).
 * 4. Generate Code.
 */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include <stdio.h>
#include <string.h>


/* Private variables ---------------------------------------------------------*/
UART_HandleTypeDef huart2; // Assumes USART2 is defined

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART2_UART_Init(void);

/**
 * @brief  The application entry point.
 * @retval int
 */
int main(void) {
  /* MCU Configuration--------------------------------------------------------*/
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();
  MX_USART2_UART_Init();

  /* User Code Begin */
  char msg[] = "\r\nSTM32 UART Echo Ready!\r\nType something and I will echo "
               "it back:\r\n";
  HAL_UART_Transmit(&huart2, (uint8_t *)msg, strlen(msg), HAL_MAX_DELAY);

  uint8_t rxBuffer[1]; // Buffer for 1 byte

  while (1) {
    /* Receive 1 byte in blocking mode (or look into Interrupt/DMA for
     * non-blocking) */
    if (HAL_UART_Receive(&huart2, rxBuffer, 1, 100) == HAL_OK) {
      // Echo the character back
      HAL_UART_Transmit(&huart2, rxBuffer, 1, HAL_MAX_DELAY);

      // Optional: Toggle LED to visualize activity (PA5 is often LD2 on Nucleo)
      HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);
    }
  }
  /* User Code End */
}

/*
 * NOTE: The following initialization functions are typically generated by
 * CubeMX. We include a skeletal reference here for understanding.
 */
static void MX_USART2_UART_Init(void) {
  huart2.Instance = USART2;
  huart2.Init.BaudRate = 115200;
  huart2.Init.WordLength = UART_WORDLENGTH_8B;
  huart2.Init.StopBits = UART_STOPBITS_1;
  huart2.Init.Parity = UART_PARITY_NONE;
  huart2.Init.Mode = UART_MODE_TX_RX;
  huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart2.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&huart2) != HAL_OK) {
    // Error_Handler();
  }
}
